#!/bin/bash

source ./env-vars
source ./util

container_id=$(get_container_id)
if [ $? -eq 0 ]
then
  (>&2 echo "Dojo container already running with container id $container_id.")
  get_notebook_list $container_id
  exit 1
fi

docker run -d \
  -it \
  --rm \
  -p 8888:8888 \
  --name dojo \
  --mount type=volume,source=$DOCKER_VOLUME_NAME,target=/dojo \
  --mount type=bind,source=$HOME/data,target=/data \
  $DOCKER_USER_NAME/$DOCKER_IMAGE_NAME >/dev/null

container_id=$(get_container_id)
sleep 5
get_notebook_list $container_id
