#!/bin/bash

source ./env-vars
source ./util

container_id=$(get_container_id)
if [ $? -eq 0 ]
then
  (>&2 echo "Dojo container already running with container id $container_id.")
  docker exec -it $container_id bash
  exit
fi

docker run -d \
  -it \
  --rm \
  --name dojo-aws \
  --mount type=volume,source=$DOCKER_VOLUME_NAME,target=/dojo \
  --mount type=bind,source=$HOME/data,target=/data \
  $DOCKER_USER_NAME/$DOCKER_IMAGE_NAME >/dev/null

container_id=$(get_container_id)
sleep 5
exit
